blog/urls.py
from django.urls import path
from .views import render_posts,post_detail

app_name = "blog"

urlpatterns = [
    path('',render_posts,name='posts'),
    path("<int:post_id>/",post_detail, name="post_detail")
] 

contact/urls.py
from django.urls import path
from .views import contact
app_name = "contact"

urlpatterns = [
    path('',contact,name='contact'),
] 

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',include('portfolio.urls'), name="home"),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from .views import home
app_name = "home"

urlpatterns = [
    path('',home,name='home'),
] 

blog/models.py
from django.db import models
import datetime
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)
    

contact/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True,widget=forms.TextInput(
        attrs={'class':'form-control','placeholder':'Nombre'}
    ))
    mail = forms.EmailField(required=True,widget=forms.EmailInput(
        attrs={'class':'form-control','placeholder':'Correo'}
    ))
    content = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'class':'form-control','placeholder':'Mensaje'}
    ))

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def render_posts(request):
    posts = Post.objects.all()
    return render(request,'posts.html',{'posts':posts})

def post_detail(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    return render(request,'post_detail.html',{"post":post})
    

contact/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.core.mail import EmailMessage
from .forms import ContactForm
# Create your views here.
def contact(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            name = request.POST.get('name','')
            mail = request.POST.get('mail','')
            content = request.POST.get('content','')
            
            # Creamos el correo 
            mail = EmailMessage(
                "Mensage desde el Portafolio",# Asunto
                f"De {name} \n y su correo es {mail} \n{content}",#Mensaje
                "portafolio.com",#Email de origen 
                ["garcetejulian3@gmail.com"],# email de destino
                reply_to=[mail]
            )
            # lo enviamos y redireccionamos 
            try:
                mail.send()
                # si todo va bien enviamos y redireccionamos a OK
                return redirect(reverse('contact:contact')+"?ok")
            except:
                # si no salio bien redireccionamos al fail
                return redirect(reverse('contact:contact')+"?fail")
                
    return render(request,'contact/contact.html',{"form":contact_form})

portfolio/views.py
from django.shortcuts import render, redirect
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

   

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date }}</h3>
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">

    <div class="my-4">
        <p>{{ post.description | safe }}</p>
    </div>

</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">

        <div class="row">
            <div class="col-3 ">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
            </div>

            <div class="col-9">
                <h2>{{ post.title }}</h2>
                <h3>{{ post.date | date:"M d Y"}}</h3>
                <p>{{ post.description | striptags | truncatechars:100 }}</p>

                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{ post.title }}</a>
            </div>
        </div>

    </div>
</div>
{% endfor %}
{% endblock %}

contact/templates/contact/contact.html
{% extends 'layout.html' %}

{% block title %} Portafolio Contacto {% endblock %}

{% block content %}
<div class="row p-4">
    <section class="bg-dark p-4 " id="contact">
        <div class="container">
            <div class="row align-items-center g-lg-5 py-5">
                <div class="col-lg-6 text-center  text-lg-start">
                    <h2 class="display-4 fw-bold lh-1 mb-3">¡Hablemos!</h2>
                    <p class="col-lg-10 fs-4">Si estás interesado en trabajar conmigo o tienes alguna pregunta, no dudes
                        en
                        contactarme a través del formulario o por correo electrónico. Estaré encantado de escuchar lo
                        que
                        tienes que decir. ¡Gracias por visitar mi sitio web!</p>
                </div>

                <div class="col-md-10 mx-auto col-lg-6">
                    <form class="p-4 p-md-5 border rounded-3 bg-black" method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="form-label">Nombre completo</label>
                            {{form.name}}
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Correo electrónico</label>
                            {{form.mail}}
                        </div>
                        <div class="mb-3">
                            <label for="message" class="form-label">Mensaje</label>
                            {{form.content}}
                        </div>
                        <button type="submit" class="btn btn-primary" style="width: 100%;">Enviar</button>
                    </form>
                </div>
            </div>
        </div>

    </section>
</div>
{% endblock %}

portfolio/templates/email_template.html
{{message}}

{{name}}

{{email}}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}


<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/julian_garcete.webp' %}" class="p-4 img-perfil" width="340px" height="340px"
            alt="">
    </div>
    <div class="col-md-8 my-auto">
        <h1>Soy <strong>Garcete Julian</strong></h1>
        <h3>Soy un Desarrollador Backend Python</h3>

        <p>Desarrollador Backend y Python con experiencia en el manejo de Flask y Django. Manejo en SQL y creación de
            CRUDs robustos. Comprometido con el aprendizaje continuo y con habilidades destacadas para trabajar en
            equipo. Busco un entorno laboral donde pueda seguir ampliando mis conocimientos y contribuir al éxito del
            equipo.</p>
        <a href="{% static 'portfolio/cv_garcete_julian2.pdf' %}" target="_blank"
            class="btn btn-primary btn-lg rounded-0 my-3">Descargar CV</a>
    </div>
</header>


<div class="row my-4 text-center">

    <h3>Mis Poyectos</h3>
    <p>Django: Estructura poderosa. Flask: Sencillez ágil.</p>

    {% for project in projects %}

    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img src="{{ project.image.url }}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>

                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light runded-0 btn-sm" target="_blank">{{project.url}}</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<div class="row my-4 text-center ">
    <div class="col-md-6 p-4">
        <h3>Habilidades y conocimientos</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-black text-light">Lenguajes: Python, SQL</li>
            <li class="list-group-item bg-black text-light">Frameworks: Flask, Django</li>
            <li class="list-group-item bg-black text-light">Desarrollo de CRUDs robustos</li>
            <li class="list-group-item bg-black text-light">Manejo de bases de datos</li>
            <li class="list-group-item bg-black text-light">Trabajo en equipo</li>
        </ul>
    </div>

    <div class="col-md-6 p-4">
        <h3>Educación</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-black text-light">Analista de Sistemas y Programacion | Combate Mborore | 2022
                a 2023
            </li>
            <li class="list-group-item bg-black text-light">Curso completo de Python 2024-De cero a Master con Python
                3/Flas7Django | UDEMY | 2023
            </li>
            <li class="list-group-item bg-black text-light">Estudio principalmente autodidacta a traves de cursos de Udemy y Youtube</li>

        </ul>
    </div>
</div>

<div class="row p-4">
    <img src="{% static 'portfolio/certificado_udemy.jpg'%}" class="img-fluid" alt="...">
</div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Portafolio Personal {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <style>
        .card-project:hover {
            border: 1px solid #fff;
            cursor: pointer;
        }
        .img-perfil{
            border: 1px solid #fff;

        }
        .bg-black{
            background: #000;
        }
        .img-cert{
            width:1100px;
            height:700px;
        }
    </style>
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}
    
    <div class="container p-4">
        {% block content %} 
        {% endblock %}
    </div>

    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">GJ</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts'%}">Blog</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'contact:contact'%}" >Contacto</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv_garcete_julian2.pdf' %}" target="_blank" >Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>